title: All Creator Blog
description: My Personal Blog
author: Hyeok Jin Park
logo: /ParkHyeokJin.github.io/static/img/avatar.png
github: https://github.com/ParkHyeokJin
about: Java developer

baseurl: "https://parkhyeokjin.github.io/"
url: "https://parkhyeokjin.github.io/"

allowsearch: true

disqus_shortname: AllCreator
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
